(ns advent-03.core)

(require '[clojure.pprint :as pp])
(require '[clojure.repl :refer :all])
(require '[clojure.string :as str])
(require '[clojure.set :as set])
(require '[clojure.test :refer :all])

(def small-input "small-input.txt")
(def large-input "large-input.txt")

(defn- read-lines [f]
  (with-open [rdr (clojure.java.io/reader f)]
    (doall(line-seq rdr))))

(def profile-times (atom {}))

(defmacro profile [name exp]
  `(let [start# (System/nanoTime)
         result# (doall ~exp)
         elapsed# (/ (double (- (System/nanoTime) start#)) 1000000.0)]
     (swap! profile-times update ~name #(+ (or % 0) elapsed#))
     result#))

(defn parse-input [input]
  (->> (read-lines input)
       (map #(re-seq #"\d" %))
       (map #(map parse-long %))))


;; Part 1
;; What's the maximum total joltage that can be generated by turning on
;; two batteries in each bank?
(defn largest-with-first [ns]
  (if (= 1 (count ns))
    (first ns)
    (+ (* 10 (first ns)) (apply max (rest ns)))))

(defn largest-pair [ns]
  (loop [m 0
         ns ns]
    (if (seq ns)
      (recur (max m (largest-with-first ns)) (rest ns))
      m)))

(defn max-joltage [input]
  (apply + (map largest-pair (parse-input input))))


;; (time (max-joltage small-input))
;; "Elapsed time: 0.511 msecs"
;; 357
;; (time (max-joltage large-input))
;; "Elapsed time: 63.5753 msecs"
;; 17443

;; Part 2
;; What's the maximum total joltage that can be generated by turning on
;; twelve batteries in each bank?

(defn to-digits [n]
  (->> n
       (str)
       (vec)
       (map str)
       (map parse-long)))

(defn to-number [ns]
  (parse-long (str/join ns)))

(defn remove-greatest [ns]
  (let [ns (vec ns)
        the-min (apply min ns)
        min-index (first (first (filter #(= the-min (second %)) (map-indexed vector ns))))
        ;; _ (println "ns" ns "the-min" the-min "min-index" min-index)
        ]
    (concat (subvec ns 0 min-index) (subvec ns (inc min-index)))))

(defn merge-number [n ns]
  (let [removed (remove-greatest ns)]
    (cons n removed)))

(defn largest-x [ns-in x]
  ;; (printf "original number: %s\n" (str/join ns-in))
  (loop [ns (drop (- (count ns-in) x) ns-in)
         remaining (take (- (count ns-in) x) ns-in)]
    (let [n (last remaining)]
      (if (nil? n)
        (to-number ns)
        (let [merged (merge-number n ns)
              old-n (to-number ns)
              new-n (to-number merged)
              ;; _ (printf "n: %d %d/%d\n" n old-n new-n)
              ]
          (recur (if (> new-n old-n) merged ns) (butlast remaining)))))))

(deftest test-small-input
  (is (= 987654321111 (largest-x (to-digits "987654321111111") 12)))
  (is (= 811111111119 (largest-x (to-digits "811111111111119") 12)))
  (is (= 434234234278 (largest-x (to-digits "234234234234278") 12)))
  (is (= 888911112111 (largest-x (to-digits "818181911112111") 12))))

(defn max-joltage-2 [input]
  (apply + (map #(largest-x %1 12) (parse-input input))))

(deftest test-max-joltage-2
  (is (= 3121910778619 (max-joltage-2 small-input)))
  (is (> 172099442692331 (max-joltage-2 large-input))))

;; 172098322241544 too low
;; 172099442692331 too low

;; 118981 

(defn largest-x-2 [ns-in x]
  (let [y (- (count ns-in) x)]
    (loop [ns ns-in
           ns-out []]
      ;; (println "ns" ns "ns-out" ns-out)
      ;; (flush)
      (if (= (count ns-out) y)
        (to-number (concat ns-out ns))
        (let [local-ns (take (inc y) ns)
          ;; _ (println "n" n "local-ns" local-ns)
          removed (remove-greatest local-ns)
          _ (println "y" y "ns" ns "local-ns" local-ns "removed" removed "ns-out" ns-out)
          _ (flush)
          ]
          (recur (rest (concat removed (drop y ns))) (conj ns-out (first removed))))))))

(deftest test-small-input-2
  (is (= 987654321111 (largest-x-2 (to-digits "987654321111111") 12)))
  (is (= 811111111119 (largest-x-2 (to-digits "811111111111119") 12)))
  (is (= 434234234278 (largest-x-2 (to-digits "234234234234278") 12)))
  (is (= 888911112111 (largest-x-2 (to-digits "818181911112111") 12))))

(defn max-joltage-3 [input]
  (apply + (map #(largest-x-2 %1 12) (parse-input input))))
