(ns advent-03.core)

(require '[clojure.pprint :as pp])
(require '[clojure.repl :refer :all])
(require '[clojure.string :as str])
(require '[clojure.set :as set])
(require '[clojure.test :refer :all])

(def small-input "small-input.txt")
(def large-input "large-input.txt")

(defn- read-lines [f]
  (with-open [rdr (clojure.java.io/reader f)]
    (doall(line-seq rdr))))

(def profile-times (atom {}))

(defmacro profile [name exp]
  `(let [start# (System/nanoTime)
         result# (doall ~exp)
         elapsed# (/ (double (- (System/nanoTime) start#)) 1000000.0)]
     (swap! profile-times update ~name #(+ (or % 0) elapsed#))
     result#))

(defn parse-input [input]
  (->> (read-lines input)
       (map #(re-seq #"\d" %))
       (map #(map parse-long %))))


;; Part 1
;; What's the maximum total joltage that can be generated by turning on
;; two batteries in each bank?
(defn largest-with-first [ns]
  (if (= 1 (count ns))
    (first ns)
    (+ (* 10 (first ns)) (apply max (rest ns)))))

(defn largest-pair [ns]
  (loop [m 0
         ns ns]
    (if (seq ns)
      (recur (max m (largest-with-first ns)) (rest ns))
      m)))

(defn max-joltage [input]
  (apply + (map largest-pair (parse-input input))))


;; (time (max-joltage small-input))
;; "Elapsed time: 0.511 msecs"
;; 357
;; (time (max-joltage large-input))
;; "Elapsed time: 63.5753 msecs"
;; 17443
